version: "3.8"

services:
  pdf-encryptor:
    image: muhpatr/pdf-encryptor:1.0.0
    container_name: pdf-encryptor
    ports:
      - "7082:7082"
    volumes:
      - ./files:/app/files
    restart: unless-stopped
    environment:
      - TZ=Asia/Jakarta